### ISSUE TITLE
WDialog 按钮颜色问题造成无法显示

### ISSUE THREAD

**Issue by jonahfang** [flutter-studio/flutter-weui#2]
采用白色主题时，android风格的对话框的按钮看不到。

**Comment by jonahfang** [comment]
更改如下:
<img width="874" alt="wx20190203-083905 2x" src="https://user-images.githubusercontent.com/16301509/52170967-3ab11080-278f-11e9-9226-6b36b7b8aafb.png">

**Comment by 2534290808** [comment]
example里是能够看到的
