### ISSUE TITLE
能否提供PreView相关组件?

### ISSUE THREAD

**Issue by jonahfang** [flutter-studio/flutter-weui#4]
非常感谢作者提供weui风格的flutter组件。在weui reactjs版本中有下列组件:
*  Preview
*  PreviewHeade
*  PreviewBody
* PreviewItem

近期有计划开发这些组件吗？

**Comment by 2534290808** [comment]
这个我会考虑的

**Comment by 2534290808** [comment]
0.1.5版本提供PreView组件

**Comment by jonahfang** [comment]
谢谢
